const { test, expect } = require('@playwright/test');

/**
 * Basic E2E Test Template
 * Generated by Dev Quality Inspector
 */

test.describe('Basic E2E Tests', () => {
  test.beforeEach(async ({ page }) => {
    // Navigate to the application
    await page.goto(process.env.BASE_URL || 'http://localhost:3000');

    // Wait for page to load
    await page.waitForLoadState('domcontentloaded');
  });

  test('should load the homepage', async ({ page }) => {
    // Wait for app to initialize
    await page.waitForTimeout(3000);

    // Check if page has content
    const body = page.locator('body');
    await expect(body).toBeVisible();

    console.log('✓ Homepage loaded successfully');
  });

  test('should be responsive', async ({ page }) => {
    // Test desktop
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.waitForTimeout(1000);

    // Test mobile
    await page.setViewportSize({ width: 375, height: 667 });
    await page.waitForTimeout(1000);

    console.log('✓ Responsive design works');
  });

  test('should have no console errors', async ({ page }) => {
    const errors = [];

    page.on('console', msg => {
      if (msg.type() === 'error') {
        errors.push(msg.text());
      }
    });

    await page.goto(process.env.BASE_URL || 'http://localhost:3000');
    await page.waitForTimeout(5000);

    const criticalErrors = errors.filter(err =>
      err.includes('Uncaught') ||
      err.includes('TypeError') ||
      err.includes('ReferenceError')
    );

    expect(criticalErrors.length).toBe(0);
    console.log('✓ No critical console errors');
  });
});
